Repository nimblehq/flutter-ic-khanh-thieu, pull requests merged in 2023-08, with the labels that each got.

#43 [#42] [Chore] Update Pull Request template and CI pipeline
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/test.yml
Labels: type : chore

#44 [Chore] Bump version to 0.1.0
  pubspec.yaml
Labels: type : chore

#40 [#4] [Chore] Set up the CD with Fastlane and GitHub Actions for iOS - part 1 of 2
  .github/workflows/ios_deploy_staging_to_firebase.yml
  .github/workflows/ios_deploy_staging_to_testflight.yml
  .github/workflows/ios_deploy_to_testflight.yml
  ios/.gitignore
  ios/Gemfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/fastlane/Constants/Environments.rb
  ios/fastlane/Fastfile
Labels: type : chore

#45 [#4] [Chore] Set up the CD with Fastlane and GitHub Actions for iOS - part 2 of 2
  .github/workflows/ios_deploy_production_to_testflight.yml
  .github/workflows/ios_deploy_to_app_store.yml
  ios/fastlane/Fastfile
Labels: type : chore

#41 [#26] [Chore] Set up the CD with GitHub Actions for Android
  .github/workflows/android_deploy_staging.yml
Labels: type : chore

#47 [Chore] Bump version to 0.2.0
  pubspec.yaml
Labels: type : chore

#51 [#9] [Backend] As a user, I can sign in with email and password
  .env.sample
  ios/Podfile.lock
  lib/api/api_service.dart
  lib/api/authentication_api_service.dart
  lib/api/repository/credential_repository.dart
  lib/api/response_decoder.dart
  lib/env.dart
  lib/model/login_model.dart
  lib/model/request/login_request.dart
  lib/model/response/login_response.dart
  lib/model/response/user_response.dart
  lib/repositories/authentication_repository.dart
  lib/usecases/login_use_case.dart
  pubspec.lock
  pubspec.yaml
  test/api/repositories/authentication_repository_test.dart
  test/api/repository/credential_repository_test.dart
  test/api/usecases/login_use_case_test.dart
  test/mocks/generate_mocks.dart
Labels: type : feature, @0.2.0

#49 [#7] [UI] As a user, I see validation errors when login
  integration_test/utils/test_util.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/screens/login/login_form.dart
  lib/screens/login/login_view_model.dart
  pubspec.lock
  pubspec.yaml
  test/screens/login/login_view_model_test.dart
Labels: type : feature, @0.2.0

#52 [Release] 0.2.0
  .env.sample
  assets/images/2.0x/splash_background.png
  assets/images/2.0x/splash_logo_white.png
  assets/images/3.0x/splash_background.png
  assets/images/3.0x/splash_logo_white.png
  assets/images/nimble_logo.png
  assets/images/splash_background.png
  assets/images/splash_logo_white.png
  integration_test/my_home_page_test.dart
  integration_test/utils/test_util.dart
  ios/Podfile.lock
  lib/api/api_service.dart
  lib/api/authentication_api_service.dart
  lib/api/repository/credential_repository.dart
  lib/api/response_decoder.dart
  lib/env.dart
  lib/l10n/app_en.arb
  lib/l10n/app_th.arb
  lib/l10n/app_vi.arb
  lib/main.dart
  lib/model/login_model.dart
  lib/model/request/login_request.dart
  lib/model/response/login_response.dart
  lib/model/response/user_response.dart
  lib/repositories/authentication_repository.dart
  lib/screens/login/login_form.dart
  lib/screens/login/login_screen.dart
  lib/screens/login/login_view_model.dart
  lib/screens/splash/splash_screen.dart
  lib/theme/app_constants.dart
  lib/theme/app_theme.dart
  lib/theme/primary_button_style.dart
  lib/theme/primary_text_field_decoration.dart
  lib/usecases/login_use_case.dart
  lib/utils/build_context_ext.dart
  pubspec.lock
  pubspec.yaml
  test/api/repositories/authentication_repository_test.dart
  test/api/repository/credential_repository_test.dart
  test/api/usecases/login_use_case_test.dart
  test/mocks/generate_mocks.dart
  test/screens/login/login_view_model_test.dart
Labels: type : release, @0.2.0

#53 [Chore] Bump version to 0.3.0
  pubspec.yaml
Labels: type : chore

#55 [#8] [UI] As a user, if I fail to log in, I see an error popup
  lib/l10n/app_en.arb
  lib/screens/login/login_form.dart
  lib/screens/login/login_screen.dart
  lib/screens/login/login_view_model.dart
  lib/theme/app_theme.dart
  lib/uimodels/app_error.dart
  lib/utils/build_context_ext.dart
  lib/utils/internet_connection_manager.dart
  lib/widgets/alert_dialog.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/generate_mocks.dart
  test/screens/login/login_view_model_test.dart
  test/utils/async_listener.dart
Labels: type : feature, @0.3.0

#56 [#14] [UI] As a logged-in user, I can see the survey list on the Home screen
  assets/images/2.0x/next.png
  assets/images/3.0x/next.png
  assets/images/dummy_avatar.png
  assets/images/dummy_background.png
  assets/images/next.png
  lib/l10n/app_en.arb
  lib/screens/home/home_footer_widget.dart
  lib/screens/home/home_header_widget.dart
  lib/screens/home/home_page_indicator_widget.dart
  lib/screens/home/home_pages_widget.dart
  lib/screens/home/home_screen.dart
  lib/theme/app_constants.dart
  lib/theme/app_theme.dart
  lib/utils/date_time_util.dart
  pubspec.lock
  pubspec.yaml
Labels: type : feature, @0.3.0

#57 [#10] [Integrate] As a user, I can sign in with email and password
  lib/di/provider/dio_provider.dart
  lib/main.dart
  lib/repositories/authentication_repository.dart
  lib/screens/home/home_screen.dart
  lib/screens/login/login_form.dart
  lib/screens/login/login_screen.dart
  lib/screens/login/login_view_model.dart
  lib/usecases/login_use_case.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/dummy_models.dart
  test/mocks/generate_mocks.dart
  test/screens/login/login_view_model_test.dart
Labels: type : feature, @0.3.0

#58 [#15] [Backend] As a logged-in user, I can see the survey list on the Home screen
  lib/api/response_decoder.dart
  lib/api/survey_api_service.dart
  lib/model/meta_model.dart
  lib/model/response/login_response.dart
  lib/model/response/meta_response.dart
  lib/model/response/survey_response.dart
  lib/model/response/surveys_container_response.dart
  lib/model/survey_model.dart
  lib/model/surveys_container_model.dart
  lib/repositories/survey_repository.dart
  lib/usecases/get_surveys_use_case.dart
  test/api/repositories/survey_repository_test.dart
  test/api/usecases/get_surveys_user_case_test.dart
  test/mocks/generate_mocks.dart
Labels: type : feature, @0.3.0

#59 [#11] [Integrate] As a user, once I have logged in, I can see the app stores the access token in the local storage
  ios/Podfile.lock
  lib/di/provider/flutter_secure_storage.dart
  lib/model/api_token.dart
  lib/model/response/login_response.dart
  lib/repositories/authentication_repository.dart
  lib/storage/secure_storage.dart
  lib/storage/secure_storage_impl.dart
  pubspec.lock
  pubspec.yaml
  test/api/repositories/authentication_repository_test.dart
  test/mocks/generate_mocks.dart
Labels: type : feature, @0.3.0

#60 [#54] [UI] As a logged in user, I can see skeleton loading animation
  lib/screens/home/home_screen.dart
  lib/screens/home/home_shimmer_loading.dart
  lib/theme/app_constants.dart
  pubspec.lock
  pubspec.yaml
Labels: type : feature, @0.3.0

#61 [Release] 0.3.0
  assets/images/2.0x/next.png
  assets/images/3.0x/next.png
  assets/images/dummy_avatar.png
  assets/images/dummy_background.png
  assets/images/next.png
  ios/Podfile.lock
  lib/api/response_decoder.dart
  lib/api/survey_api_service.dart
  lib/di/provider/dio_provider.dart
  lib/di/provider/flutter_secure_storage.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/model/api_token.dart
  lib/model/meta_model.dart
  lib/model/response/login_response.dart
  lib/model/response/meta_response.dart
  lib/model/response/survey_response.dart
  lib/model/response/surveys_container_response.dart
  lib/model/survey_model.dart
  lib/model/surveys_container_model.dart
  lib/repositories/authentication_repository.dart
  lib/repositories/survey_repository.dart
  lib/screens/home/home_footer_widget.dart
  lib/screens/home/home_header_widget.dart
  lib/screens/home/home_page_indicator_widget.dart
  lib/screens/home/home_pages_widget.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/home_shimmer_loading.dart
  lib/screens/login/login_form.dart
  lib/screens/login/login_screen.dart
  lib/screens/login/login_view_model.dart
  lib/storage/secure_storage.dart
  lib/storage/secure_storage_impl.dart
  lib/theme/app_constants.dart
  lib/theme/app_theme.dart
  lib/uimodels/app_error.dart
  lib/usecases/get_surveys_use_case.dart
  lib/usecases/login_use_case.dart
  lib/utils/build_context_ext.dart
  lib/utils/date_time_util.dart
  lib/utils/internet_connection_manager.dart
  lib/widgets/alert_dialog.dart
  pubspec.lock
  pubspec.yaml
  test/api/repositories/authentication_repository_test.dart
  test/api/repositories/survey_repository_test.dart
  test/api/usecases/get_surveys_user_case_test.dart
  test/mocks/dummy_models.dart
  test/mocks/generate_mocks.dart
  test/screens/login/login_view_model_test.dart
  test/utils/async_listener.dart
Labels: type : release, @0.3.0

#62 [Chore] Bump version to 0.4.0
  pubspec.yaml
Labels: type : chore

#63 [#12] [Backend] As a user, I can see the app automatically refreshes my expired access token
  lib/api/authentication_api_service.dart
  lib/api/data_sources/token_data_source.dart
  lib/api/interceptor/auth_interceptor.dart
  lib/di/provider/dio_provider.dart
  lib/model/request/refresh_token_request.dart
  lib/model/response/token_response.dart
  lib/repositories/authentication_repository.dart
  lib/repositories/survey_repository.dart
  test/api/data_sources/token_data_source_test.dart
  test/api/repositories/authentication_repository_test.dart
  test/mocks/generate_mocks.dart
Labels: type : feature, @0.4.0

#65 [#31] [#64] [Integrate] As a logged-in user, I can see the survey list on the Home screen
  assets/images/dummy_background.png
  assets/images/placeholder.png
  ios/Podfile.lock
  lib/api/data_sources/token_data_source.dart
  lib/api/response_decoder.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/model/response/meta_response.dart
  lib/model/response/survey_response.dart
  lib/model/response/surveys_container_response.dart
  lib/model/survey_model.dart
  lib/repositories/survey_repository.dart
  lib/screens/home/home_footer_widget.dart
  lib/screens/home/home_page_indicator_widget.dart
  lib/screens/home/home_pages_widget.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/home_state.dart
  lib/screens/home/home_view_model.dart
  lib/storage/secure_storage_impl.dart
  lib/storage/survey_storage.dart
  lib/usecases/base/base_use_case.dart
  lib/usecases/base/use_case_result.dart
  lib/usecases/get_cached_surveys_use_case.dart
  lib/usecases/get_surveys_use_case.dart
  pubspec.lock
  pubspec.yaml
  test/api/repositories/survey_repository_test.dart
  test/api/usecases/get_cached_surveys_use_case_test.dart
  test/api/usecases/get_surveys_user_case_test.dart
  test/mocks/generate_mocks.dart
  test/screens/home/home_view_model_test.dart
Labels: type : feature, @0.4.0

#67 [#16] [Integrate] As a logged-in user, I can pull down to refresh the survey list
  lib/screens/home/home_screen.dart
  lib/screens/home/home_view_model.dart
  test/screens/home/home_view_model_test.dart
Labels: type : feature, @0.4.0

#66 [#13] [Integrate] As a logged-in user, I can see the Home screen when I relaunch the app
  lib/api/data_sources/token_data_source.dart
  lib/model/api_token.dart
  lib/model/request/refresh_token_request.dart
  lib/screens/splash/splash_screen.dart
  lib/screens/splash/splash_view_model.dart
  lib/storage/secure_storage.dart
  lib/storage/secure_storage_impl.dart
  lib/usecases/check_user_logged_in_use_case.dart
  lib/utils/serializer/api_token_serializer.dart
  lib/utils/serializer/serializable.dart
  test/api/data_sources/token_data_source_test.dart
  test/api/usecases/check_user_logged_in_use_case_test.dart
  test/mocks/generate_mocks.dart
  test/screens/splash/splash_view_model_test.dart
Labels: type : feature, @0.4.0

#68 [Release] 0.4.0
  assets/images/dummy_background.png
  assets/images/placeholder.png
  ios/Podfile.lock
  lib/api/authentication_api_service.dart
  lib/api/data_sources/token_data_source.dart
  lib/api/interceptor/auth_interceptor.dart
  lib/api/response_decoder.dart
  lib/di/provider/dio_provider.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/model/api_token.dart
  lib/model/request/refresh_token_request.dart
  lib/model/response/meta_response.dart
  lib/model/response/survey_response.dart
  lib/model/response/surveys_container_response.dart
  lib/model/response/token_response.dart
  lib/model/survey_model.dart
  lib/repositories/authentication_repository.dart
  lib/repositories/survey_repository.dart
  lib/screens/home/home_footer_widget.dart
  lib/screens/home/home_page_indicator_widget.dart
  lib/screens/home/home_pages_widget.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/home_state.dart
  lib/screens/home/home_view_model.dart
  lib/screens/splash/splash_screen.dart
  lib/screens/splash/splash_view_model.dart
  lib/storage/secure_storage.dart
  lib/storage/secure_storage_impl.dart
  lib/storage/survey_storage.dart
  lib/usecases/base/base_use_case.dart
  lib/usecases/base/use_case_result.dart
  lib/usecases/check_user_logged_in_use_case.dart
  lib/usecases/get_cached_surveys_use_case.dart
  lib/usecases/get_surveys_use_case.dart
  lib/utils/serializer/api_token_serializer.dart
  lib/utils/serializer/serializable.dart
  pubspec.lock
  pubspec.yaml
  test/api/data_sources/token_data_source_test.dart
  test/api/repositories/authentication_repository_test.dart
  test/api/repositories/survey_repository_test.dart
  test/api/usecases/check_user_logged_in_use_case_test.dart
  test/api/usecases/get_cached_surveys_use_case_test.dart
  test/api/usecases/get_surveys_user_case_test.dart
  test/mocks/generate_mocks.dart
  test/screens/home/home_view_model_test.dart
  test/screens/splash/splash_view_model_test.dart
Labels: type : release, @0.4.0

#69 Bump version to 0.5.0
  pubspec.yaml
Labels: type : chore

#70 [#19] [UI] As a logged-in user, I can see the Survey Detail screen
  lib/l10n/app_en.arb
  lib/main.dart
  lib/screens/app_route.dart
  lib/screens/home/home_pages_widget.dart
  lib/screens/home/home_screen.dart
  lib/screens/login/login_screen.dart
  lib/screens/splash/splash_screen.dart
  lib/screens/survey/survey_screen.dart
Labels: type : feature, @0.5.0

#71 [#17] [Integrate] As a logged-in user, I can scroll to load more surveys
  lib/screens/home/home_pages_widget.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/home_state.dart
  lib/screens/home/home_view_model.dart
  lib/usecases/base/use_case_result.dart
  test/screens/home/home_view_model_test.dart
Labels: type : feature, @0.5.0

#73 [#72] [UI] As the user, I can see the survey question
  assets/images/dummy_background.png
  assets/svg/close_button.svg
  lib/l10n/app_en.arb
  lib/main.dart
  lib/screens/app_route.dart
  lib/screens/survey/survey_detail_screen.dart
  lib/screens/survey/survey_question_widget.dart
  lib/screens/survey/survey_screen.dart
  lib/theme/app_constants.dart
Labels: type : feature, @0.5.0

#74 [Release] 0.5.0
  assets/images/dummy_background.png
  assets/svg/close_button.svg
  lib/l10n/app_en.arb
  lib/main.dart
  lib/screens/app_route.dart
  lib/screens/home/home_pages_widget.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/home_state.dart
  lib/screens/home/home_view_model.dart
  lib/screens/login/login_screen.dart
  lib/screens/splash/splash_screen.dart
  lib/screens/survey/survey_detail_screen.dart
  lib/screens/survey/survey_question_widget.dart
  lib/screens/survey/survey_screen.dart
  lib/theme/app_constants.dart
  lib/usecases/base/use_case_result.dart
  pubspec.yaml
  test/screens/home/home_view_model_test.dart
Labels: type : release

#75 [Chore] Bump version to 0.6.0
  pubspec.yaml
Labels: type : chore
